---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "go-web-app-config"
  namespace: "default"
  labels:
    app: "go-web-app-config"
data:
  ADDRESS: "10.36.2.5:6379"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "go-web-app"
  namespace: "default"
  labels:
    app: "go-web-app"
spec:
  selector:
    matchLabels:
      app: "go-web-app"
  replicas: 3
  template:
    metadata:
      labels:
        app: "go-web-app"
    spec:
      containers:
        - name: "app"
          image: "ashishbhoi/go-web-app:latest"
          env:
            - name: "ADDRESS"
              valueFrom:
                configMapKeyRef:
                  key: "ADDRESS"
                  name: "go-web-app-config"